# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chenqi_app', '0002_auto_20180530_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='Pro_leave_bug',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='\u9057\u7559\u7684\u4e3b\u8981\u95ee\u9898'),
        ),
        migrations.AlterField(
            model_name='pro',
            name='Pro_lines',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='\u4ea7\u7ebf\u4eba\u5458'),
        ),
        migrations.AlterField(
            model_name='pro',
            name='Pro_nedfol_bug',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='\u9700\u8981\u4ea7\u7ebf\u8ddf\u8e2a\u7684\u95ee\u9898'),
        ),
        migrations.AlterField(
            model_name='pro',
            name='Pro_nedre_bug',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='\u672a\u89e3\u51b3\u7684\u4e3b\u8981\u95ee\u9898'),
        ),
        migrations.AlterField(
            model_name='pro',
            name='Pro_safe_end',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='\u5b89\u5168\u7ed3\u8bba'),
        ),
        migrations.AlterField(
            model_name='pro',
            name='Pro_zs',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='\u4e2d\u8bd5\u53c2\u4e0e\u4eba\u5458'),
        ),
        migrations.AlterField(
            model_name='pro',
            name='Pro_zs_end',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='\u6d4b\u8bd5\u7ed3\u8bba'),
        ),
    ]
