# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chenqi_app', '0003_auto_20180531_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='Pro_DI',
            field=models.FloatField(verbose_name='\u9879\u76eeDI\u503c'),
        ),
    ]
