# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chenqi_app', '0004_auto_20180605_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugSort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_sort1', models.IntegerField(blank=True, null=True, verbose_name='\u786c\u4ef6')),
                ('bug_sort2', models.IntegerField(blank=True, null=True, verbose_name='\u5ba2\u6237\u7aef')),
                ('bug_sort3', models.IntegerField(blank=True, null=True, verbose_name='\u4e1a\u52a1\u529f\u80fd')),
                ('bug_sort4', models.IntegerField(blank=True, null=True, verbose_name='\u5b89\u5168\u6027')),
                ('bug_sort5', models.IntegerField(blank=True, null=True, verbose_name='\u6613\u7528\u6027')),
                ('bug_sort6', models.IntegerField(blank=True, null=True, verbose_name='\u4e92\u8054\u4e92\u901a')),
                ('bug_sort7', models.IntegerField(blank=True, null=True, verbose_name='\u5176\u4ed6\u4ea7\u54c1\u95ee\u9898')),
                ('Pro_zs_one', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chenqi_app.Pro')),
            ],
        ),
    ]
