# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chenqi_app', '0008_auto_20180612_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='Pro_People_pr_old',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='\u8d1f\u8d23\u4eba_\u8001\u7684'),
        ),
    ]
